# Generated by Django 4.0.6 on 2022-07-21 17:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCharge',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.datetimemodel')),
                ('charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
            ],
            bases=('video.datetimemodel',),
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('datetimemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.datetimemodel')),
                ('title', models.CharField(help_text='Video Title', max_length=50)),
                ('file', models.FileField(help_text='Video File should have mp4 or mkv extension and should not exceed 1 GB', upload_to='videos', validators=[src.video.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])])),
                ('video_length', models.IntegerField(help_text='Video Duration in seconds')),
                ('video_size', models.DecimalField(decimal_places=2, help_text='Video Size in bytes', max_digits=9)),
                ('ref_charge', models.ForeignKey(help_text='Video Charge', null=True, on_delete=django.db.models.deletion.CASCADE, to='video.videocharge')),
            ],
            bases=('video.datetimemodel',),
        ),
    ]
